"""Plan generation agent.

Takes a ProjectCreate description and returns a structured plan
(phases → steps) using Pydantic AI with a configurable LLM model.

No DB access. No side effects. Pure generation.
"""

import json
import re

from pydantic import BaseModel, Field
from pydantic_ai import Agent

from app.agents._model import get_model

from app.schemas.enums import StepType
from app.schemas.phase import Phase
from app.schemas.project import ProjectCreate
from app.schemas.step import Step

# ---------------------------------------------------------------------------
# Agent output schema — lean model for LLM structured output
# ---------------------------------------------------------------------------


class PlanStubSubStep(BaseModel):
    """A short stub sub-step generated up-front so the user sees an
    expected breakdown of each step. Kept intentionally terse: the heavy
    sub-step generation still happens lazily via
    :func:`app.agents.substeps.generate_sub_steps` when the user opens a
    step."""

    name: str = Field(..., description="Very short stub name (3-6 words)")
    objective: str = Field(
        ..., description="One short sentence describing the stub's intent"
    )


class PlanStep(BaseModel):
    """A single actionable step for the LLM to generate."""

    name: str = Field(..., description="Short step name (shown on card)")
    objective: str = Field(..., description="One-line description of what this step achieves")
    step_type: StepType = Field(..., description="Category: frontend, backend, infra, or other")
    sub_steps: list[PlanStubSubStep] = Field(
        default_factory=list,
        description=(
            "2 to 3 short stub sub-steps that hint at the expected breakdown. "
            "Hidden by default in the UI -- shown when the user expands the step."
        ),
    )


class PlanPhase(BaseModel):
    """A logical phase grouping several steps."""

    name: str = Field(..., description="Phase name (e.g. 'Foundations', 'Core Backend')")
    steps: list[PlanStep] = Field(
        ..., min_length=1, description="Ordered list of steps in this phase"
    )


class PlanOutput(BaseModel):
    """Complete project plan generated by the agent."""

    phases: list[PlanPhase] = Field(
        ..., min_length=2, description="Ordered list of phases (at least 2)"
    )


# ---------------------------------------------------------------------------
# System instructions
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a senior software project planner.
Your job is to generate a structured, realistic project plan
from a project description.

Rules:
- Generate 3 to 6 phases, ordered logically from setup to delivery.
- Each phase has 2 to 5 steps. Keep steps actionable and concrete.
- Steps must be progressively detailed: early phases are broader,
  later phases are more specific.
- For EACH step, also generate 2 to 3 short stub sub-steps that hint at
  the expected breakdown (the UI keeps them collapsed by default).
  Stubs are placeholders -- keep names very short (3-6 words) and
  objectives to one short sentence. They will be replaced by detailed
  sub-steps later when the user opens the step.
- Assign the correct step_type: frontend, backend, infra, or other.
- Phase names should be clear and descriptive (e.g. "Project Setup",
  "Core Backend", "Frontend UI", "Integration & Testing").
- Do NOT include authentication unless explicitly mentioned in constraints.
- Do NOT over-engineer. Favor simplicity and progressive disclosure.
- Stay within the stated objective and constraints. Do not invent features.

You MUST respond with ONLY a JSON object (no markdown, no explanation) matching
this exact schema:
{
  "phases": [
    {
      "name": "Phase Name",
      "steps": [
        {
          "name": "Step Name",
          "objective": "What this step achieves",
          "step_type": "backend",
          "sub_steps": [
            {"name": "Stub 1", "objective": "What this stub covers"},
            {"name": "Stub 2", "objective": "What this stub covers"}
          ]
        }
      ]
    }
  ]
}

Valid step_type values: "frontend", "backend", "infra", "other".
"""

# ---------------------------------------------------------------------------
# Agent definition
# ---------------------------------------------------------------------------

_MODEL = get_model()

plan_agent: Agent[None, str] = Agent(
    _MODEL,
    output_type=str,
    system_prompt=_SYSTEM_PROMPT,
    retries=1,
    defer_model_check=True,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_JSON_BLOCK_RE = re.compile(r"```(?:json)?\s*(.*?)```", re.DOTALL)


def _extract_json(text: str) -> dict:
    """Extract JSON from LLM response (may be wrapped in markdown fences)."""
    # Try markdown code block first
    m = _JSON_BLOCK_RE.search(text)
    if m:
        return json.loads(m.group(1))
    # Try raw JSON
    return json.loads(text)


def _to_domain_phases(output: PlanOutput) -> list[Phase]:
    """Convert agent output to domain Phase/Step schemas."""
    phases: list[Phase] = []
    for phase_idx, p in enumerate(output.phases):
        steps: list[Step] = []
        for step_idx, s in enumerate(p.steps):
            sub_steps: list[Step] = []
            for sub_idx, sub in enumerate(s.sub_steps[:3]):
                # Stubs inherit the parent's step_type; the UI doesn't
                # need a per-stub category and the LLM tends to omit it.
                sub_steps.append(
                    Step(
                        name=sub.name,
                        objective=sub.objective,
                        step_type=s.step_type,
                        order=sub_idx,
                    )
                )
            steps.append(
                Step(
                    name=s.name,
                    objective=s.objective,
                    step_type=s.step_type,
                    order=step_idx,
                    sub_steps=sub_steps,
                )
            )
        phases.append(Phase(name=p.name, order=phase_idx, steps=steps))
    return phases


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def generate_plan(project: ProjectCreate, instructions: str = "") -> list[Phase]:
    """Generate a project plan from a project description.

    Returns a list of Phase objects with Steps, ready to be attached to a Project.
    No DB interaction — the caller is responsible for persistence.
    """
    user_prompt = f"""\
Project: {project.name}
Description: {project.description}
Objective: {project.objective}
"""
    if project.business_context:
        user_prompt += f"Business context: {project.business_context}\n"
    if project.constraints:
        user_prompt += f"Constraints: {project.constraints}\n"
    if instructions.strip():
        user_prompt += f"\nAdditional instructions:\n{instructions.strip()}\n"

    result = await plan_agent.run(user_prompt)
    parsed = _extract_json(result.output)
    plan = PlanOutput.model_validate(parsed)
    return _to_domain_phases(plan)


# ---------------------------------------------------------------------------
# Phase-scoped re-planner
# ---------------------------------------------------------------------------


class PhaseStepsOutput(BaseModel):
    """Output schema for the phase-scoped re-planner."""

    steps: list[PlanStep] = Field(
        ..., min_length=1, description="Replacement steps for the phase (ordered)."
    )


_PHASE_REGEN_SYSTEM_PROMPT = """\
You re-plan the steps of ONE phase inside an existing project plan,
without touching any other phase.

You are given:
- The project metadata (name, description, objective, constraints).
- The full plan tree, so you understand the surrounding phases.
- The name of the phase to regenerate.
- The user's new instruction (e.g. "use Reflex for the UI").

Rules:
- Generate 2 to 5 fresh steps for the target phase only.
- Do NOT renumber or reference other phases.
- Do NOT generate sub-steps.
- Re-use the same step names if the previous wording is still appropriate;
  only change names when the meaning actually shifts.
- Assign step_type: frontend, backend, infra, or other.

Respond with ONLY a JSON object (no markdown, no commentary) matching:
{
  "steps": [
    {"name": "Step Name", "objective": "What this step achieves", "step_type": "frontend"}
  ]
}
"""


_phase_regen_agent: Agent[None, str] = Agent(
    _MODEL,
    output_type=str,
    system_prompt=_PHASE_REGEN_SYSTEM_PROMPT,
    retries=1,
    defer_model_check=True,
)


async def regenerate_phase_steps(
    *,
    project: ProjectCreate,
    plan_tree: str,
    phase_name: str,
    instructions: str,
) -> list[Step]:
    """Re-plan the steps of a single phase. Returns ordered ``Step`` objects.

    ``plan_tree`` is a textual snapshot of the current plan (use the
    same renderer as the chat agent) so the LLM keeps context. The
    caller swaps the resulting steps into the target ``PhaseDB``.
    """
    user_prompt = f"""\
Project: {project.name}
Description: {project.description}
Objective: {project.objective}
"""
    if project.business_context:
        user_prompt += f"Business context: {project.business_context}\n"
    if project.constraints:
        user_prompt += f"Constraints: {project.constraints}\n"
    if plan_tree.strip():
        user_prompt += f"\nCurrent full plan:\n{plan_tree.strip()}\n"
    user_prompt += f"\nPhase to regenerate: {phase_name}\n"
    if instructions.strip():
        user_prompt += f"\nUser instruction: {instructions.strip()}\n"

    result = await _phase_regen_agent.run(user_prompt)
    parsed = _extract_json(result.output)
    payload = PhaseStepsOutput.model_validate(parsed)
    return [
        Step(
            name=s.name,
            objective=s.objective,
            step_type=s.step_type,
            order=idx,
        )
        for idx, s in enumerate(payload.steps)
    ]
